.TH AKONADI "1" "July 2015" "Akonadi 1.13.0" "User Commands"
.SH NAME
akonadictl \- Akonadi server manipulation tool
.SH SYNOPSIS
.B akonadictl
[\fI\,command\/\fR]
.SH DESCRIPTION
.SS "Commands:"
.TP
start
: Starts the Akonadi server with all its processes
.TP
stop
: Stops the Akonadi server and all its processes cleanly
.TP
restart
: Restart Akonadi server with all its processes
.TP
status
: Shows a status overview of the Akonadi server
.TP
vacuum
: Vacuum internal storage (WARNING: needs a lot of time and disk space!)
.TP
fsck
: Check (and attempt to fix) consistency of the internal storage (can take some time)
.SH OPTIONS
.SS "General options:"
.TP
\fB\-h\fR [ \fB\-\-help\fR ]
show this help message
.TP
\fB\-\-version\fR
show version information
.SS "Multi-instance options:"
.TP
\fB\-\-instance\fR arg
Namespace for starting multiple Akonadi instances in
the same user session
